# Changes here will be overwritten by Copier
_commit: '9689455'
_src_path: git@github.com:python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: timkpaine
project_description: CSP adapter for Discord
project_name: csp adapter discord
python_version_primary: '3.11'
team: the csp-adapter-discord authors
